### ISSUE TITLE
ERS should be usable through python

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/ers#19]

**Comment by plasorak** [comment]
Current ERS python bindings (https://github.com/DUNE-DAQ/ers/blob/develop/python/) use the `boost/python` library to create python modules, however the choice from DUNE-DAQ is to use [pybind11](https://github.com/pybind/pybind11), so we need to migrate code in the `python/` directory to use `pybind11`. There are examples in [`timing`](https://github.com/DUNE-DAQ/timing/tree/develop/pybindsrc) that may be useful.

**Comment by AlanTWatson** [comment]
We've got past the thing that was blocking us. Should be able to post a development version soon.

**Comment by plasorak** [comment]
This is done, as far as I know
